{
 "title": "Node.js Observability",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Errores HTTP 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "http_errors_total" }
   ]
  },
  {
   "title": "Tiempos de respuesta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_bucket[1m])"
    }
   ]
  }
 ]
}